configuration:
  swagger:
    app: 'EventPort'
    version: 1.1.0
    description: 'Always free event organization and management system.'
    developer: 'Almir Mulalić'
    email: 'almir.mulalic@ibu.edu.ba'

spring:
  application:
    name: eventport-api

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: eventport
      username: "root"
      password: "535VZMsvMK*Es3Gw3#2U"
